application: basicrtlist
version: 1
runtime: python
api_version: 1

inbound_services:
- channel_presence

handlers:
- url: /style
  static_dir: style

- url: /js
  static_dir: js

- url: .*
  script: main.py
